Oncognier/cogroom-fe

- .babelrc
- package-lock.json
- package.json
- Closes #9 
- babel 의존성 제거
- babel 설정 파일 제거
> [FIX] @emotion/babel-plugin 제거 #9

- package.json
- public/mockServiceWorker.js
- src/app/MSWProvider.tsx
- src/app/layout.tsx
- src/mocks/browser.ts
- src/mocks/handlers.ts
- src/mocks/server.ts
- Closes #8 
- init msw .public
- mocks 파일 생성 후 클라이언트, server, handler 설정 
- 최상위 layout 에 server 설정 및 MSWProvider(client) 설정
> [FEAT] msw 설정 #8

- src/app/MSWProvider.tsx
- src/app/layout.tsx
- src/mocks/browser.ts
- src/mocks/server.ts
- Closes #14 
- import 구문 줄바꿈 
- require 구문 import 로 수정
- any -> HotModule로 타입 지정 
지금 타입이 HotModule이 MSWProvider에 있는데, 여기에서만 쓰이니까 안빼도 될 것 같기도 하고,
types 폴더에 types/msw/types.ts 만들어서 관리하는 게 좋을 지 원빈님에게 물어보고 싶네요.
저는 types로 빼는게 맞다고 생각합니다. 한번 의견주시고 주시는 대로 바로 반영하겠습니다.!
> [FIX] MSW ESlint 오류 수정 #14

- src/api/axios/axiosInstance.ts
- src/api/axios/interceptors.ts
- src/api/axios/types.ts
- Closes #18 
- import 줄바꿈 추가
- ErrorResponseData 에서 [key: string] : any 삭제
- 응답 시 에러에 있는 any -> AxiosError<ErrorResponseData> 로 변경
뒷일을 부탁하겠습니다.
> [FIX] axios 관련 eslint 오류 수정 #18

- src/app/layout.tsx
- src/styles/font.ts
- src/styles/typography.ts
- Closes #21 
- localfont 설정의 위치를 서버 영역으로 이동시켰습니다. (font.ts)
> [FIX] Pretendard 폰트 적용 #21

- src/constants/api/api.ts
- Closes #23 
- API 명세서에 있는 API URL 정의
추가적으로 더 정의할 것이 있다면 말씀해주세요.
아직 KAKAO 관련해서는 나온게 없다보니까 CLIENT_ID 같이 정의 해두는게 맞나 싶어서 일단 API 명세서 상에 있는 것만 했습니다.
혹시 URL 틀릴 수도 있어서 검토 부탁드리겠습니다.
> [FEAT] 엔드포인트 상수 정의 #23

- src/components/atoms/Switch/Switch.stories.tsx
- src/components/atoms/Switch/Switch.styled.ts
- src/components/atoms/Switch/Switch.tsx
- Closes #33 
- Switch 컴포넌트 구현
> [FEAT] Switch 컴포넌트 구현 #33

- .github/workflows/discord.yml
- Closes #70 
- 구현한 내용 설명1
- 구현한 내용 설명2
> [FIX] 디스코드 알림 워크플로우 버그 해결 #70

- src/api/dailyApis.ts
- src/app/daily/_components/Question/Question.tsx
- src/app/daily/page.tsx
- src/mocks/data/daily/getDailyData.ts
- src/types/daily.ts
- Closes #72  
- submitDailyAnswer assignedQuestionId 추가 및 페이지 적용
- editDailyAnswer assignedQuestionId 추가 및 페이지 적용
- mocks 데이터 assignedQuestionId 값 추가 및 데이터 값 변경
> [FEAT] daily apis assignedquestionid #72

- src/app/daily/_components/Question/Question.tsx
- src/mocks/handlers/daily.ts
- Closes #78 
- daily 페이지 enter 로직 삭제했습니다.
이번 기회로 enter 제출이 한글지원 시 에러가 발생할 수 있다는 걸 알게 되었네요. :)
- mocks daily handlers 수정 이걸 dailyDataNotAnswered 랑 dailyDataAnswered 둘다 만들어두고 주석을 푸는식으로 했는데 생각 보다 불편해서 바꿨습니다.
> [REFACTOR] delete enter handler #78

- src/components/atoms/TabBar/TabBar.stories.tsx
- src/components/atoms/TabBar/TabBar.styled.ts
- src/components/atoms/TabBar/TabBar.tsx
- Closes #87 
- TabBar 컴포넌트 구현
> [FEAT] TabBar 컴포넌트 구현 #87

- src/app/mypage/layout.tsx
- src/components/organisms/AuthGuard/AuthGuard.styled.ts
- src/components/organisms/AuthGuard/AuthGuard.tsx
- Closes #85 
- AuthGuard 컴포넌트 생성 -> 로그인 접근 제한 컴포넌트
- 마이페이지에서 로그인 유무 검사하여 AuthGuard 렌더링
> [FEAT] 비회원이 마이페이지 직접 접근 시 접근 제한 추가 #85

- src/hooks/api/daily/useGetDaily.ts
- src/hooks/api/streak/useGetStreakDays.ts
- Closes #99 
- 'use client' 제거
hooks 의 일관성을 위해 삭제했습니다.
- enabled 요소 추가
> [FEAT] daily streaks api enabled #99

- src/constants/api.ts
- Closes #114 
- 토큰 재발급 api 엔드포인트 수정
> [FIX] 토큰 재발급 api 엔드포인트 변경 #114

- src/api/fileApis.ts
- src/app/(shared)/(standard)/mypage/setting/_components/SettingProfile/SettingProfile.tsx
- src/app/(shared)/(standard)/mypage/setting/page.tsx
- src/components/atoms/IconButton/IconButton.tsx
- src/constants/api.ts
- src/hooks/api/file/useUploadFileToS3.ts
- src/mocks/data/file/getPresignedUrlData.ts
- src/mocks/handlers/file.ts
- src/types/file.ts
- Closes #80 
- presigned url api 응답값 변경
- 엔드포인트 수정
> [FEAT] 이미지 업로드 API 수정 #80

- src/app/(shared)/(standard)/admin/contents/page.tsx
- src/app/(shared)/(standard)/admin/layout.styled.ts
- src/app/(shared)/(standard)/admin/layout.tsx
- src/app/(shared)/(standard)/admin/notices/page.tsx
- src/app/(shared)/(standard)/admin/page.tsx
- src/app/(shared)/(standard)/admin/payments/page.tsx
- src/app/(shared)/(standard)/admin/users/page.tsx
- Closes #138 
- 어드민 페이지 라우팅 구조 구현
> [FEAT] 어드민 페이지 라우팅 구조 구현 #138

- src/components/molecules/NumberPagination/NumberPagination.stories.tsx
- src/components/molecules/NumberPagination/NumberPagination.styled.ts
- src/components/molecules/NumberPagination/NumberPagination.tsx
- src/constants/common.ts
- src/utils/pagination.ts
- Closes #147 
- NumberPagination 컴포넌트 구현
- NumberPagination 스토리 작성
- pagination 유틸 함수 추가
- 페이지 그룹 크기 상수로 정의
> [FEAT] NumberPagination 컴포넌트 구현 #147

- src/components/atoms/Check/Check.stories.tsx
- src/components/atoms/Check/Check.styled.ts
- src/components/atoms/Check/Check.tsx
- src/components/atoms/Checkbox/Checkbox.stories.tsx
- src/components/atoms/Checkbox/Checkbox.styled.ts
- src/components/atoms/Checkbox/Checkbox.tsx
- Closes #153 
- Check 컴포넌트명 수정 : Checkbox(다른 Checkbox 컴포넌트와 이름 겹침, 파일명과 다름) -> Check (파일명과 같도록 통일)
- Check 컴포넌트 사이즈 수정 : sm, md -> nm, sm
> [REFACTOR] Check 컴포넌트명 수정 #153

- src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.styled.ts
- src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.tsx
- src/constants/common.ts
- src/types/daily.ts
- Closes #162 
- DailyListRow 컴포넌트 구현
> [FEAT] DailyListRow 컴포넌트 구현 #162

- src/app/(shared)/(standard)/daily/_components/Calendar/Calendar.tsx
- src/app/(shared)/(standard)/mypage/activity/daily/_components/DailyQuestionCard/DailyQuestionCard.tsx
- src/components/atoms/OutlinedButton/OutlinedButton.tsx
- src/components/atoms/SolidButton/SolidButton.tsx
- src/components/organisms/Modal/Login/Login.tsx
- Closes #178 
- outline solid button align 기본값 변경
- 해당 값 변경으로 변경이 필요한 컴포넌트 수정
최대한 찾아봤는데 일단 이정도 입니다. ㅜ.ㅜ
> [FIX] outline solid align #178

- src/app/(shared)/(anomaly)/(home)/_components/Daily/Daily.styled.ts
- src/app/(shared)/(anomaly)/(home)/_components/Daily/Daily.tsx
- src/app/(shared)/(standard)/community/page.styled.ts
- src/app/(shared)/(standard)/community/page.tsx
- src/app/(shared)/(standard)/content/page.styled.ts
- src/app/(shared)/(standard)/content/page.tsx
- src/constants/image.ts
- Closes #179 
- main - daily 이미지 화질 개선 및 text 분리
- community 이미지 화질 개선 및 text 분리
- content 이미지 화질 개선 및 text 분리
이미지 너무 무거운거 같긴해요.. 저도 좀 걸리던데요 .. ?
> [FIX] content community banner and daily main banner #179

- src/app/ModalProvider.tsx
- src/components/organisms/Modal/Daily/FirstAnswer/DailyFirstAnswer.styled.ts
- src/hooks/api/daily/useEditDailyAnswer.ts
- src/hooks/api/daily/useSubmitDailyAnswer.ts
- src/mocks/data/daily/editDailyAnswer.ts
- src/mocks/data/daily/submitDailyAnswer.ts
- Closes #143 
- modalconfig alert wrapper 수정
- 데일리 답변 제출 시 & 수정 시 에러 모달 적용
- 해당 mocks 적용
음 공백에 대한 오류 코드가 명세서랑 달라서 확인 해봐야할 것 같긴 합니다.
> [FEAT] daily submit error modal #143

- src/app/(shared)/(standard)/daily/_components/Question/Question.styled.ts
- src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
- src/app/(shared)/(standard)/daily/_components/Streak/Streak.styled.tsx
- src/app/(shared)/(standard)/daily/_components/Streak/Streak.tsx
- src/constants/image.ts
- Closes #203 
- question ui 변경 사항 반영
- streaks 문구 변경
> [FEAT] daily 개선 사항 반영 #203

- src/components/organisms/Modal/Daily/DailyShare/DailyShare.tsx
- src/components/organisms/Modal/Error/Error.tsx
- src/hooks/api/admin/useCreateDailyQuestions.ts
- src/hooks/api/admin/useDeleteMember.ts
- src/hooks/api/auth/useCheckEmailVerified.ts
- src/hooks/api/auth/useLogin.ts
- src/hooks/api/auth/useLogout.ts
- src/hooks/api/daily/useEditDailyAnswer.ts
- src/hooks/api/daily/useSubmitDailyAnswer.ts
- src/hooks/api/file/useUploadFileToS3.ts
- src/hooks/api/member/useCheckNickname.ts
- src/utils/validators/setValidationError.ts
- Closes #197 
- 에러 모달 문구 변경
- api 에러 처리 모달로 전체 변경
> [FEAT] 에러 모달을 통한 api 에러 처리 #197

- src/api/axios/axiosInstance.ts
- src/components/molecules/Textarea/Textarea.styled.ts
- src/components/molecules/Textarea/Textarea.tsx
- src/constants/queryKeys.ts
- src/hooks/api/admin/useCreateDailyQuestions.ts
- src/hooks/api/admin/useGetDailyQuestions.ts
- src/hooks/api/admin/useGetMemberDailyQuestions.ts
- src/hooks/api/auth/useLogin.ts
- src/hooks/api/auth/useSignup.ts
- src/styles/globalStyles.ts
- Closes #209 
- Textarea 컴포넌트에 리사이즈 가능 여부 제어 기능 추가 -> 자기소개 입력란 고정
- 회원가입, 로그인 성공 시 리디렉션 url 수정
- 데일리 질문 추가 성공 시 라우팅 추가 및 캐시 무효화 추가
- qs import 방법 변경
- button 태그 폰트 미적용 버그 해결
> [REFACTOR] 프론트 이슈사항 해결 #209

- src/app/(shared)/(standard)/daily/_components/Calendar/Calendar.tsx
- src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
- src/app/(shared)/(standard)/daily/page.tsx
- Closes #216 
- 내 리포트 보러가기 비회원시 로그인 모달 연결
저번에 충돌 해결하다가 이렇게 된게 아닌가 ... 아무튼 넵 ㅜ.ㅜ
- 공유하기 비회원시 로그인 모달 연결
> [FIX] daily go report onclick #216

- src/constants/validationMessages.ts
- src/utils/validators/setValidationError.ts
- Closes #230 
- validationMessages에 중복된 이메일 추가 -> 중복된 이메일 예외 처리 추가
- 예외 모달에 에러 메시지 띄우는 것으로 변경
> [FIX] Handle Duplicate Email Error #230

- src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
- src/components/organisms/Modal/Daily/FirstAnswer/DailyFirstAnswer.styled.ts
- src/components/organisms/Modal/Daily/FirstAnswer/DailyFirstAnswer.tsx
- src/components/organisms/Modal/modalConfig.ts
- Closes #233 
- dailyfirstAnswer 생성 및 config 적용
- daily - 답변 란 focus 함수 제거 및 제출 시 첫 답변 일 때 로직 추가
> [FIX] modify first answer modal flow #233

- src/app/(shared)/(standard)/admin/users/_components/UserListRow/UserListRow.styled.ts
- src/app/(shared)/(standard)/admin/users/_components/UserListRow/UserListRow.tsx
- src/app/(shared)/(standard)/admin/users/_components/UserTableHeader/UserTableHeader.tsx
- src/utils/formatText.ts
- Closes #232 
- 숫자를 6자리 문자열로 포맷하는 유틸 함수 추가
- 회원 번호 ui 추가
> [FEAT] Add Unique ID UI to Admin > User Management Page #232

- src/app/(shared)/(standard)/(legal)/privacy/page.styled.ts
- src/app/(shared)/(standard)/(legal)/privacy/page.tsx
- Closes #238 
- 개인정보 처리방침 페이지 구현
> [FEAT] Implement Privacy Page #238

- src/constants/common.ts
- Closes #275
- common.ts 충돌 해결
> [STYLE] prettier 충돌 해결 #275

- src/app/layout.tsx
> [FEAT] GTM 추가 #278

- src/app/NotifyComponent.tsx
- src/app/layout.tsx
- src/components/organisms/Modal/Notify/Notify.styled.ts
- src/components/organisms/Modal/Notify/Notify.tsx
- src/components/organisms/Modal/modalConfig.ts
- Closes #280 
- 로그인 에러 공지 모달 추가
> [FEAT] 로그인 에러 공지 모달 추가 #280

- src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.styled.ts
- src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.tsx
- src/components/organisms/Modal/CommunityDelete/CommunityDelete.tsx
- src/hooks/api/post/useDeletePost.ts
- Closes #https://github.com/Oncognier/cogroom-fe/issues/477
- 공용 컴포넌트 `DropdownList` 사용하여 화면 우측 점세개 더보기 메뉴아이콘 클릭 시 수정/삭제/관리자의 경우 강제로삭제 기능 제공
> [FEAT] 커뮤니티 > 게시글 조회 페이지 내 수정/삭제 기능 추가 #477

- package-lock.json
- src/components/organisms/Editor/CustomToolbar/Popup/ColorPopup.tsx
- src/components/organisms/Editor/Editor.tsx
- https://github.com/Oncognier/cogroom-fe/issues/464
- 위 이슈의 항목 중 처리된 것은 두 가지 입니다.
- 컬러 팝업 색상 표 변경 
- 이미지 드래그 앤 드랍 기능 추가
- 새 창으로 열기 기능
- tiptap 에디터 내에서 링크 사용 시 무조건 새 창으로 열리게 덮어씌워지고 있는 것 같습니다.
제가 체크박스를 선택하지 않아도 무조건 _blank 가 추가되고 있어 확인 후 수정하도록 하겠습니다.
> [FEAT] 에디터 > 새 창으로 열기 기능 추가 및 기타 수정 #464

- src/app/(shared)/(standard)/daily/_components/Question/Question.styled.ts
- src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
- src/app/(shared)/(standard)/mypage/community/comments/page.tsx
- src/app/(shared)/(standard)/mypage/community/layout.tsx
- src/app/(shared)/(standard)/mypage/community/posts/page.styled.ts
- src/app/(shared)/(standard)/mypage/community/posts/page.tsx
- src/app/(shared)/(standard)/mypage/community/saves/page.tsx
- Closes #498 
- 마이페이지에서 필터 제외하고 데이터가 없을 시 EmptyState 띄우도록 변경
- 게시글 조회 시 데일리 질문 답변란 스타일 수정
- 마이페이지 > 커뮤니티 > 좋아요 페이지 초기 진입 라우팅 주소 수정
> [FEAT] 커뮤니티 관련 자잘한 이슈 수정 #498

- src/app/(shared)/(standard)/community/post/[id]/_components/PostContent/PostContent.styled.ts
- src/app/(shared)/(standard)/community/post/[id]/_components/PostContent/PostContent.tsx
- src/components/organisms/Editor/CustomLink.ts
- src/components/organisms/Editor/CustomToolbar/Popup/LinkPopup.tsx
- src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarPalette.tsx
- src/components/organisms/Editor/Editor.tsx
- Closes #https://github.com/Oncognier/cogroom-fe/issues/495
- tiptap 에디터 의 Link 기능이 기본적으로 모든 링크는 새 창으로 열리게 작동하고 있습니다.
- 새 창으로 열리지 않게 props 를 줬음에도 컨트롤이 불가하여 커스텀 링크 함수를 제작했습니다!
- 추가로 a 링크에 대한 css 도 추가했습니다.
> [FEAT] 에디터 > 링크 새창으로 열기 기능추가 #495

- package-lock.json
- package.json
- src/components/organisms/Editor/CustomImage.tsx
- src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarParagraph.tsx
- Closes #https://github.com/Oncognier/cogroom-fe/issues/505
- 이미지만 별도로 정렬가능
- 텍스트&이미지 드래그 시 이미지,텍스트 모두 정렬 가능
https://github.com/user-attachments/assets/00ed8036-3551-498e-9385-13fabc8f2b62
> [FEAT] 에디터 > 이미지 정렬 기능 #505

- src/app/(shared)/(standard)/community/_components/PostList/PostList.styled.ts
- Closes #517
- ButtonFilter 스크롤 가능하도록 변경
https://github.com/user-attachments/assets/5b2f14b9-1fc2-477d-b59f-e885a70744cc
> [FEAT] 커뮤니티 반응형 추가 #517

- src/app/(shared)/(standard)/mypage/layout.styled.ts
- src/app/(shared)/(standard)/mypage/layout.tsx
- Closes #530 
- svg 아이콘 사용방식 변경 (svg 태그에 스타일 -> 부모 div에 스타일)
> [FIX] 마이페이지 모바일 메뉴 드롭다운 아이콘 사이즈 버그 #530

- src/app/(shared)/(standard)/community/post/[id]/_components/PostContent/PostContent.styled.ts
- src/components/organisms/Editor/CustomToolbar/CustomToolbar.tsx
- src/components/organisms/Editor/Editor.tsx
- src/hooks/useCommunityWriteLogic.ts
- src/utils/postUtils.ts
- Closes #https://github.com/Oncognier/cogroom-fe/issues/543
- 게시글 수정 > 이미지 삭제 시 모든 경우(ex-똑같은 파일명이 두개가 등록되어 있다던지 등등) url 포함되도록 수정처리 완료
- `calculateDeleteUrls` 함수 수정
> [FIX] 에디터 > 삭제한 이미지 deleteUrl 에 추가되지 않는 이슈 #543

- src/components/organisms/Editor/CustomToolbar/Popup/PopupStyles.styled.ts
- Closes #561 
- isActive일 경우 hover 색상은 일단 제거하였습니다. 나중에 팝업 관련해서 정확하게 디자인 요청 드리겠습니다!
> [FIX] 에디터 툴바 팝업 스타일 수정 #561

- src/components/organisms/Editor/CustomToolbar/Sections/CustomToolbarPalette.tsx
`release/1.4.1` 브랜치에서 릴리즈된 변경사항을 `develop` 브랜치에도 반영하기 위한 머지 PR입니다.
- #566
- 1.4.1 릴리즈 이슈: #568
> [RELEASE] Sync release/1.4.1 → develop
