- src/components/atoms/IconButton/IconButton.stories.tsx
- src/components/atoms/IconButton/IconButton.styled.ts
- src/components/atoms/IconButton/IconButton.tsx
- src/components/atoms/Radio/Radio.stories.tsx
- src/components/atoms/Radio/Radio.styled.ts
- src/components/atoms/Radio/Radio.tsx
- src/components/atoms/Switch/Switch.stories.tsx
- src/components/atoms/Switch/Switch.styled.ts
- src/components/atoms/Switch/Switch.tsx
- src/components/atoms/TextButton/TextButton.stories.tsx
- src/components/atoms/TextButton/TextButton.styled.ts
- src/components/atoms/TextButton/TextButton.tsx
- src/styles/InteractionOverlay.styled.ts
- Closes #39 
- IconButton에서 background의 패딩이 디자인과 달라 수정하였습니다
- 컴포넌트 별 interactionColor 조건 처리를 추가하여 interactionColor 고정으로 변경
- disable 명칭을 isDisabled로 변경
디자인 시스템 전반에서 button 등 기본적으로 disabled 속성을 제공하는 컴포넌트의 경우, CSS에서는 &:disabled를 사용하는 방식이 직관적이고 일관성이 있다고 판단했습니다.
이에 따라 props 네이밍도 disable보다는 불리언 의미가 명확하게 드러나는 isDisabled로 통일하는 것이 가독성과 의도를 전달하는 데 더 적절하다고 생각되어 변경하였습니다.
관련해서 다른 의견 있으시면 편하게 공유해 주세요!
- disable 일때 커서 디폴트로 변경
- TextButton에 fillContainer 사이즈 추가
> [FEAT] 디자인 팀 피드백 반영 #39

- src/components/atoms/AvatarPerson/AvatarPerson.stories.tsx
- src/components/atoms/AvatarPerson/AvatarPerson.styled.ts
- src/components/atoms/AvatarPerson/AvatarPerson.tsx
- src/constants/image.ts
- Closes #37 
- AvatarPerson 컴포넌트 구현
- 기본 아바타 이미지 상수로 정의 ( 추후 도메인 설정되면 주소 변경 )
> [FEAT] AvatarPerson 컴포넌트 구현 #37

- src/app/layout.tsx
- src/components/molecules/Input/Input.tsx
- src/components/organisms/Modal/Base/Base.stories.tsx
- src/components/organisms/Modal/Base/Base.styled.ts
- src/components/organisms/Modal/Base/Base.tsx
- src/components/organisms/Modal/Base/ModalInstance/ModalInstance.styled.ts
- src/components/organisms/Modal/Base/ModalInstance/ModalInstance.tsx
- src/components/organisms/Modal/Login/Login.tsx
- src/components/organisms/Modal/modalConfig.ts
- src/lib/query/QueryProvider.tsx
- src/stores/createModalStore.ts
- src/stores/useModalStore.ts
- src/types/modalTypes.ts
- Closes #52
- 모달 렌더링 구조를 추상화하여 재사용 가능하게 만들고,
- 상태 관리와 UI 구현 간 결합도를 낮춰 테스트 가능성과 유연성을 확보했습니다.
```js
export function createModalStore<T extends Record<string, unknown>>() {
return create<ModalStore>(...) // Zustand 기반 store 생성
}
```
다양한 모달 타입을 받아 useModalStore를 생성해주는 팩토리 역할을 합니다. 어떤 모달 그룹이든 필요할 때마다 원하는 구조로 상태 관리 인스턴스를 생성할 수 있습니다.
AppModalProps, AdminModalProps, MarketingModalProps 등 모달 그룹이 여러개 생긴다면 그룹마다의 별도 store를 생성할 수 있어 역할 분리와 확장성에 유리합니다.
전역 store에 의존하지 않고, 필요한 곳에 독립적인 store를 선언해 사용할 수 있습니다.
테스트/Storybook 환경에서도 모달 상태를 격리된 형태로 주입하여 사용 가능합니다.
```js
// 사용자용 모달 상태
export const useUserModalStore = createModalStore<UserModalProps>();
// 관리자용 모달 상태
export const useAdminModalStore = createModalStore<AdminModalProps>();
```
```js
// modalConfig.ts
import type { ModalMap } from …
```
> [FEAT] 기본 Modal 및 상태 관리 로직 구현 #52

- .github/workflows/discord.yml
- Closes #66 
GitHub Actions를 통해 develop, master 브랜치의 배포 상태를 Discord로 알림받는 기능을 추가했습니다.
- 배포 성공 시 초록색, 실패 시 빨간색으로 구분
- 배포 환경, 브랜치명, 저장소, 배포 URL, 커밋 해시 정보 포함
- deployment_status 이벤트 발생 시 자동으로 알림 전송
> [FEAT] cd 설정 - Vercel 배포 시 디스코드 알림 #66

- .github/workflows/discord.yml
- src/app/daily/layout.styled.ts
- src/app/daily/layout.tsx
- src/app/daily/page.styled.ts
- src/app/daily/page.tsx
- src/app/mypage/_components/MyPageBreadcrumb/MyPageBreadcrumb.tsx
- src/app/mypage/_components/Sidebar/Sidebar.styled.ts
- src/app/mypage/_components/Sidebar/Sidebar.tsx
- src/app/mypage/_components/Sidebar/SidebarNavItem/SidebarNavItem.styled.ts
- src/app/mypage/_components/Sidebar/SidebarNavItem/SidebarNavItem.tsx
- src/app/mypage/layout.styled.ts
- src/app/mypage/layout.tsx
- src/app/mypage/page.tsx
- src/app/mypage/setting/_components/EmailForm/EmailForm.styled.ts
- src/app/mypage/setting/_components/EmailForm/EmailForm.tsx
- src/app/mypage/setting/page.styled.ts
- src/app/mypage/setting/page.tsx
- Closes #76
- 사용자 정보 수정 -> 이메일 인증 X 시 저장버튼 disable처리
- 마이페이지 사이드바 스타일 수정
- 사이드바 use client
- 마이페이지에 Breadcrumb 추가
- discord 배포 알림 url 커스텀 도메인으로 변경
- 마이페이지 > 개인정보 설정 버튼 size md로 변경
- page, layout 스타일 파일 분리
styled.ts -> page.styled.ts, layout.styled.ts
> [FEAT] 프론트 이슈 해결 및 리팩토링 #76

- src/api/authApis.ts
- src/app/mypage/_components/Sidebar/Sidebar.tsx
- src/components/atoms/OutlinedButton/OutlinedButton.styled.ts
- src/components/atoms/OutlinedButton/OutlinedButton.tsx
- src/components/organisms/Modal/Logout/Logout.styled.ts
- src/components/organisms/Modal/Logout/Logout.tsx
- src/components/organisms/Modal/Signup/Steps/CheckEmail/CheckEmail.tsx
- src/components/organisms/Modal/modalConfig.ts
- src/constants/queryKeys.ts
- src/hooks/api/auth/useLogout.ts
- src/mocks/data/auth/logoutData.ts
- src/mocks/handlers/auth.ts
- Closes #86 
로그아웃 시, 사용자 정보 관련 캐시를 함께 삭제하도록 처리했습니다.
```js
const AUTH_QUERY_KEYS = {
AUTH: ['auth'],
AUTH_REISSUE: ['auth', 'reissue'],
} as const;
const MEMBER_QUERY_KEYS = {
MEMBER: ['member'],
MEMBER_SUMMARY: ['member', 'info', 'summary'],
MEMBER_INFO: ['member', 'info'],
} as const;
```
반복적인 쿼리 키 사용을 간소화하기 위해 AUTH_QUERY_KEYS.AUTH 및 MEMBER_QUERY_KEYS.MEMBER 등 상위 단위의 키를 추가로 정의했습니다.
로그아웃 이후에도 브라우저에는 HttpOnly 리프레시 토큰이 남아있기 때문에, 새로고침 시 자동으로 토큰 재발급 API가 호출됩니다.
이 경우 정상적으로 로그아웃 상태를 테스트하려면, reissueToken API의 모킹 응답을 실패(예: 401 Unauthorized)로 설정해주셔야 합니다.
로그아웃 모달에서 OutlinedButton이 lg 사이즈이면서 fillContainer 속성을 사용하고 있어, 해당 상황에 맞게 OutlinedButton 컴포넌트의 fillContainer 스타일을 수정했습니다.
따로 이슈파서 한번 싹 바꿔야할 것 같아요.
> [FEAT] 로그아웃 구현 #86

- src/components/organisms/Header/Header.tsx
- src/components/organisms/Header/RightNav/RightNav.tsx
- src/hooks/api/auth/useLogin.ts
- src/hooks/api/auth/useSignup.ts
- src/utils/api/prefetchAuthAndUser.ts
- Closes #101 
- 로그인 및 회원가입 성공 시 라우팅 처리가 누락되어 있어 해당 로직을 추가했습니다.
(이전 로그인 로직 수정 중 빠졌던 부분입니다..ㅠ)
- prefetch를 통해 로그인 상태를 판별할 때 accessToken이 저장되지 않아
로그인이 되지 않은 것처럼 보이는 문제가 있어, accessToken 저장 로직도 추가했습니다.
> [FEAT] accessToken 저장 및 로그인/회원가입 후 라우팅 처리 개선 #101

- src/app/(shared)/(standard)/mypage/purchase/layout.styled.ts
- src/app/(shared)/(standard)/mypage/purchase/layout.tsx
- src/app/(shared)/(standard)/mypage/purchase/page.styled.ts
- src/app/(shared)/(standard)/mypage/purchase/page.tsx
- Closes #98
- 구매 기록 화면 구현
- EmptyState 넣어뒀습니다!
```js
<S.PurchaseContainer>
<S.Heading>구매 기록</S.Heading>
</S.PurchaseContainer>
```
이 부분을 layout.ts 파일로 뺄지 고민됩니다! 마이페이지 > 커뮤니티 활동 같은 경우에는 레이아웃으로 빠질 것 같아서요!
> [FEAT] 마이페이지 > 구매 기록 구현 #98

- src/app/(shared)/(standard)/mypage/community/comments/page.tsx
- src/app/(shared)/(standard)/mypage/community/layout.styled.ts
- src/app/(shared)/(standard)/mypage/community/layout.tsx
- src/app/(shared)/(standard)/mypage/community/likes/page.tsx
- src/app/(shared)/(standard)/mypage/community/page.tsx
- src/app/(shared)/(standard)/mypage/community/posts/page.tsx
- src/components/molecules/TabBarList/TabBarList.styled.ts
- src/components/molecules/TabBarList/TabBarList.tsx
- Closes #96 
- TabBarList 컴포넌트 구현
TabBarList는 내부에서 usePathname과 useRouter를 사용하고 있어, Storybook에서 스토리를 작성하려면 next/navigation을 별도로 mock 처리해야 합니다. 복잡한 설정을 피하기 위해 이번에는 스토리 작성을 생략했습니다. 다만, 필요하다고 생각되면 해당 설정을 진행하도록 하겠습니다. 의견 부탁드립니다!
- 사용자가 /mypage/community 로 들어올 경우를 대비해서 /posts로 redirect 시켰습니다!
- 각 페이지(posts, comments, likes)에 EmptyState 컴포넌트를 넣었습니다
> [FEAT] 마이페이지 > 커뮤니티 활동 구현 #96

- src/api/authApis.ts
- src/api/axios/interceptors.ts
- src/utils/api/prefetchAuthAndUser.ts
- Closes #116 
- useAuth false 시 헤더에 들어가있는 토큰 제거
- next/headers로 prefetch 시 쿠키 가져오기
> [FIX] 토큰 재발급 버그 해결 #116

- src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingGroup.styled.ts
- src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingGroup.tsx
- src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingItem/SettingItem.styled.ts
- src/app/(shared)/(standard)/mypage/notification/_components/SettingGroup/SettingItem/SettingItem.tsx
- src/app/(shared)/(standard)/mypage/notification/layout.styled.ts
- src/app/(shared)/(standard)/mypage/notification/layout.tsx
- src/app/(shared)/(standard)/mypage/notification/page.styled.ts
- src/app/(shared)/(standard)/mypage/notification/page.tsx
- Closes #97 
- 알림 리스트, 아이템 컴포넌트 구현
- 푸시 및 카톡 알림 페이지 구현
> [FEAT] 마이페이지 > 푸시 및 카톡 알림 구현 #97

- src/api/memberApis.ts
- src/app/(shared)/(standard)/mypage/activity/contents/page.tsx
- src/app/(shared)/(standard)/mypage/activity/daily/_components/DailyQuestionCard/DailyQuestionCard.styled.ts
- src/app/(shared)/(standard)/mypage/activity/daily/_components/DailyQuestionCard/DailyQuestionCard.tsx
- src/app/(shared)/(standard)/mypage/activity/daily/page.styled.ts
- src/app/(shared)/(standard)/mypage/activity/daily/page.tsx
- src/app/(shared)/(standard)/mypage/activity/layout.styled.ts
- src/app/(shared)/(standard)/mypage/activity/layout.tsx
- src/app/(shared)/(standard)/mypage/activity/page.tsx
- src/app/(shared)/(standard)/mypage/history/page.tsx
- src/app/(shared)/(standard)/mypage/setting/page.tsx
- src/components/atoms/OutlinedButton/OutlinedButton.stories.tsx
- src/components/atoms/OutlinedButton/OutlinedButton.styled.ts
- src/components/atoms/OutlinedButton/OutlinedButton.tsx
- src/components/molecules/Textarea/Textarea.stories.tsx
- src/components/molecules/Textarea/Textarea.styled.ts
- src/components/molecules/Textarea/Textarea.tsx
- src/constants/api.ts
- src/constants/common.ts
- src/constants/queryKeys.ts
- src/hooks/api/member/useGetUserDaily.ts
- src/hooks/api/member/useGetUserInfo.ts
- src/hooks/api/member/useGetUserSummary.ts
- src/mocks/data/member/getUserDailyData.ts
- src/mocks/handlers/member.ts
- src/types/member.ts
- src/utils/formatDay.ts
- Closes #113 
유저의 데일리 질문 및 답변을 리스트로 받아올 수 있도록 API 연동 로직을 구현했습니다.
- MM/DD 형식으로 날짜를 포맷하는 함수
- 요일(월~일)로 변환하는 함수
→ dayjs 기반으로 유틸 함수로 분리했습니다.
기존 history 경로를 activity로 변경하여 기능 목적에 더 맞도록 수정했습니다.
- size 속성(sm, md, lg) 추가
디자인팀과 높이 및 resize 정책에 대한 협의가 필요합니다.
예: 고정 높이 vs 글자 수에 따라 자동 확장 등
=> 협의 후 결과 : minHeight 추가 및 autoResize 추가로 글자 수에 따라 자동 확장 가능하도록 변경
- fillContainer 옵션 사용 시 아이콘이 있을 경우 justify-content: space-between 처리되도록 수정했습니다.
> [FEAT] 마이페이지 > 학습 및 활동기록 #113

- src/components/atoms/Checkbox/Checkbox.tsx
- src/components/atoms/DropdownItem/DropdownItem.styled.ts
- src/components/atoms/DropdownItem/DropdownItem.tsx
- src/components/atoms/Radio/Radio.tsx
- src/components/molecules/DropdownList/DropdownList.styled.ts
- src/components/molecules/DropdownList/DropdownList.tsx
- src/components/molecules/Select/Select.stories.tsx
- src/components/molecules/Select/Select.styled.ts
- src/components/molecules/Select/Select.tsx
- src/components/molecules/Select/SelectTagList/SelectTag/SelectTag.styled.ts
- src/components/molecules/Select/SelectTagList/SelectTag/SelectTag.tsx
- src/components/molecules/Select/SelectTagList/SelectTagList.styled.ts
- src/components/molecules/Select/SelectTagList/SelectTagList.tsx
- src/hooks/useDropdown.ts
- src/styles/foundation.ts
- src/styles/types.ts
- src/types/common.ts
- Closes #150 
- useDropdown 훅 구현
- shadow에 normal 옵션 추가
- Checkbox, Radio 컴포넌트에 tabIndex props를 추가했습니다.
드롭다운 내에서 키보드 접근 시, 드롭다운 아이템에 포커스가 한 번 갔다면 이후 Tab 키를 눌렀을 때 Checkbox나 Radio로 포커스가 이동하지 않도록 하기 위함입니다!
현재는 Checkbox와 Radio에만 적용했지만, 추후 필요 시 다른 컴포넌트에도 확장하거나 전반적인 포커스 흐름을 고려해 리팩토링이 필요할 수 있습니다.
- Select 컴포넌트 구현
일단 구현이 급해서 리팩토링을 많이 하지는 못했어요.. 3차 이후에 리팩토링 해보도록 하겠습니다!
> [FEAT] Select 컴포넌트 구현 #150

- src/api/adminApi.ts
- src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.tsx
- src/app/(shared)/(standard)/admin/users/[memberId]/daily/_components/DailyTableHeader/DailyTableHeader.styled.ts
- src/app/(shared)/(standard)/admin/users/[memberId]/daily/_components/DailyTableHeader/DailyTableHeader.tsx
- src/app/(shared)/(standard)/admin/users/[memberId]/daily/page.styled.ts
- src/app/(shared)/(standard)/admin/users/[memberId]/daily/page.tsx
- src/constants/common.ts
- src/constants/queryKeys.ts
- src/hooks/api/admin/useGetMemberDailyQuestions.ts
- src/mocks/data/admin/getMemberDailyQuestionsData.ts
- src/mocks/handlers/admin.ts
- src/types/admin.ts
- src/types/form.ts
- Closes #164 
- 사용자 데일리 콘텐츠 조회 api 구현
- 회원관리 > 데일리 콘텐츠 페이지 구현
일단 구현하는게 급해서 리팩토링은 못했습니당.. 리팩토링은 나중에 하도록 하겠습니다!
select 크기 같은 경우도 어드민쪽은 디자인에 많이 신경 쓸 필요가 없다구 하셔서 일단 빠르게 구현하기 위해 임의대로 구현해놨어요!
> [FEAT] 어드민 > 회원관리 > 데일리콘텐츠 구현 #164

- src/app/(shared)/(anomaly)/(home)/_components/Community/Community.tsx
- src/app/(shared)/(anomaly)/(home)/_components/Content/Carousel/CarouselCard.styled.ts
- src/app/(shared)/(anomaly)/(home)/_components/Daily/Daily.tsx
- src/app/(shared)/(standard)/community/page.tsx
- src/app/(shared)/(standard)/content/page.tsx
- src/app/(shared)/(standard)/mypage/_components/Sidebar/SidebarNavItem/SidebarNavItem.styled.ts
- src/components/molecules/Breadcrumb/Breadcrumb.styled.ts
- src/components/organisms/Footer/Footer.styled.ts
- src/components/organisms/Header/NavItem/NavItem.styled.ts
- src/styles/globalStyles.ts
- Closes #199 
- main - community & daily 링크 연결
- content page 배너 외부 링크 연결
- community page 배너 외부 링크 연결
- globalstyle a 태그 text-decoration, outline 에 none 적용
외부 링크는 새탭이 열리도록 설정했습니다.
보니까 outline : none 은 대부분 쓰이는거 같은데 globalstyle 에서 관리해도 될 것 같습니다.
> [FEAT] banner link #199

- src/app/(shared)/(standard)/admin/_components/DailyListRow/DailyListRow.styled.ts
- src/app/(shared)/(standard)/admin/users/_components/UserListRow/UserListRow.styled.ts
- src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
- src/components/organisms/Modal/Daily/FirstAnswer/DailyFirstAnswer.styled.ts
- src/components/organisms/Modal/Daily/FirstAnswer/DailyFirstAnswer.tsx
- src/components/organisms/Modal/modalConfig.ts
- src/constants/validationMessages.ts
- src/hooks/api/auth/useLogin.ts
- src/hooks/api/auth/useSignup.ts
- src/utils/validators/setValidationError.ts
`release/0.0.2` 브랜치에서 릴리즈된 변경사항을 `develop` 브랜치에도 반영하기 위한 머지 PR입니다.
릴리즈 과정에서 수정된 버그 3건이 누락되지 않도록 개발 브랜치와의 이력 정합성을 맞추기 위함입니다.
- [FIX] 로그인/회원가입 후 뒤로가기 시 OAuth callback 페이지 라우팅 스택 제거 (#228)
- [FIX] 데일리 첫 답변 제출 시 모달 플로우 수정 (#233)
- [FIX] 중복된 이메일 입력 시 예외 처리 추가 (#230)
- 0.0.1 QA 이슈: #213
- 0.0.2 QA 이슈: #236
> [RELEASE] Sync release/0.0.2 → develop

- src/app/(shared)/(standard)/(legal)/marketing/page.styled.ts
- src/app/(shared)/(standard)/(legal)/marketing/page.tsx
- Closes #245 
- marketing page
마케팅은 다른 legal 페이지와는 다르게 따로 165px 만큼의 margin-bottom 이 있어서 따로 추가했습니다.
content 내용 지금 contentNumber 만 구분했는데 내용도 구분해서 할까요?
> [FEAT] marketing page #245

- src/hooks/api/daily/useEditDailyAnswer.ts
- src/hooks/api/daily/useSubmitDailyAnswer.ts
- Closes #261 
- 제출, 수정 시 유효성 모달에 서브 문구 제거 ( error -> alert 모달로 변경 )
> [FEAT] 데일리 유효성 에러모달 서브문구 제거 #261

- src/components/organisms/Modal/Signup/Signup.tsx
- src/components/organisms/Modal/Signup/Steps/CheckEmail/CheckEmail.tsx
- src/components/organisms/Modal/Signup/Steps/InputEmail/InputEmail.tsx
- Closes #259 
- CheckEmail 버튼 문구 변경
- InputEmail placeholder 변경
> [FEAT] 회원가입 단계 문구 수정 #259

- src/api/postApis.ts
- src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.tsx
- src/app/(shared)/(standard)/community/write/_components/CategorySelector/CategorySelector.styled.ts
- src/app/(shared)/(standard)/community/write/_components/CategorySelector/CategorySelector.tsx
- src/app/(shared)/(standard)/community/write/_components/DailyQuestionCard/DailyQuestionCard.tsx
- src/app/(shared)/(standard)/community/write/_components/PostEditor/PostEditor.styled.ts
- src/app/(shared)/(standard)/community/write/_components/PostEditor/PostEditor.tsx
- src/app/(shared)/(standard)/community/write/_components/TitleInput/TitleInput.tsx
- src/app/(shared)/(standard)/community/write/page.tsx
- src/components/organisms/Editor/CustomImage.tsx
- src/components/organisms/Editor/Editor.tsx
- src/constants/api.ts
- src/hooks/api/post/useGetPost.ts
- src/hooks/api/post/useUpdatePost.ts
- src/hooks/useCommunityWriteLogic.ts
- src/types/communityWrite.ts
- src/types/post.ts
- src/utils/postUtils.ts
- Closes #https://github.com/Oncognier/cogroom-fe/issues/446
- 기존 게시글 업로드 페이지를 활용한 수정 페이지 구현
- `/community/write?edit=64&type=daily`
- 게시글 수정 시 전송해야하는 deleteUrlList[] 의 경우 기존 이미지와 새 이미지를 비교하여 삭제할 이미지 URL 목록을 생성하여 전송
- 사용자가 데일리 공유했던 게시글을 수정할 경우 다른 카테고리로 이동 가능
- 게시글 수정 API 엔드포인트 변경 예정입니다!!!!!!!!!!!!! 
담당자 현진님, 기간 미정.
등록/수정 차이에 따른 UI 및 API 로 응답값 보내는것 까지는 완성되어있습니다.
- `Editor.tsx` 내에 useEffect 로직 설명
```
useEffect(() => {
if (editor && value !== editor.getHTML()) {
editor.commands.setContent(value);
}
}, [editor, value]);
if (!editor) {
return null;
}
return (
<S.EditorWrapper className={className}>
<CustomToolbar editor={editor} />
<S.EditorContent height={height}>
<EditorContent editor={editor} />
</S.EditorContent>
</S.EditorWrapper>
);
```
이유 : TipTap의 useEditor는 content를 초기화 시 한 번만 반영합니다. …
> [FEAT] 커뮤니티 > 글 수정페이지 추가 #446

- src/app/(shared)/(standard)/daily/_components/Question/Question.tsx
- src/app/(shared)/(standard)/daily/_components/Question/_components/InputCount.styled.ts
- src/app/(shared)/(standard)/daily/_components/Question/_components/InputCount.tsx
- src/constants/common.ts
- src/hooks/useTextLimiter.ts
- Closes #487 
- 글자수 100에서 200으로 변경
추후 구독 상태에 따라 달라지는건 나중에 하는걸로 했고 뭔가 지금 있는 글자수 제한 로직이 너무 의존성이 높은것 같아서 낮춰보려는 노력을 했는데
잘 된건지 모르겠네요 .. 어려워요..  더 좋은 방식 계속 생각해볼게요.
저는 이게 나중에 다른 글자수 제한 (커뮤니티 - 댓글, 게시판 제목) 과 같은 글자수 제한이 있는 곳에도 쓰일 줄 알고 그 상황을 대비해 만든거였는데 음 ... 여기에만 쓰는거면 이렇게 안하는 것도 맞지 않나 싶기도 하네요.
백엔드는 아직 200자 제한으로 올린것 같지 않아서 지금은 아마 100자 제한으로 밖에 제출 및 수정이 가능할 겁니다.
> [FEAT] daily answer character limit #487

- src/api/commentApis.ts
- src/app/(shared)/(standard)/community/post/[id]/_components/PostComments/PostComments.styled.ts
- src/app/(shared)/(standard)/community/post/[id]/_components/PostComments/PostComments.tsx
- src/app/(shared)/(standard)/community/post/[id]/_components/PostLikesSaved/PostLikesSaved.styled.ts
- src/app/(shared)/(standard)/community/post/[id]/page.tsx
- src/components/molecules/CommentField/CommentField.styled.ts
- src/components/molecules/CommentField/CommentField.tsx
- src/components/molecules/CommentItem/CommentItem.styled.ts
- src/components/molecules/CommentItem/CommentItem.tsx
- src/components/molecules/CommentList/CommentList.styled.ts
- src/components/molecules/CommentList/CommentList.tsx
- src/components/organisms/Modal/CommunityDelete/CommunityDelete.tsx
- src/constants/api.ts
- src/hooks/api/comment/useCreateComment.ts
- src/hooks/api/comment/useDeleteComment.ts
- src/hooks/api/comment/useDeleteCommentLike.ts
- src/hooks/api/comment/useGetComments.ts
- src/hooks/api/comment/useToggleCommentLike.ts
- src/hooks/api/comment/useUpdateComment.ts
- src/hooks/api/post/useCreatePost.ts
- src/types/comment.ts
- Closes #https://github.com/Oncognier/cogroom-fe/issues/463
- 댓글 조회/수정/삭제/좋아요 기능
- 대댓글 조회/수정/삭제/좋아요 기능
- 부모 댓글 5개를 기준으로 무한스크롤 구현
- response data 중 status(댓글상태)에 따른 UI 구현
- 댓글/대댓글 createdAt 기준 내림차순 정렬
- 댓글 삭제 시 '삭제하시겠어요?' 컨펌 얼럿 추가
- 게시글 등록 시 '작성되었어요!' 얼럿 추가 
- 익명 게시글에 익명 댓글/대댓글 기능 추가 
https://github.com/user-attachments/assets/473eb5de-7334-46e8-8d9b-f45746b908ed
https://github.com/user-attachments/assets/30f9bf02-b0c8-4e48-848c-faf272fad1b6
익명 댓글 /대댓글
https://github.com/user-attachments/assets/98a6b2d0-01b2-436f-bfbd-20d929b5cda8
- CommentItem 은 추후 리팩토링 해놓겠읍니다..
> [FEAT] 커뮤니티 > 게시글 조회 페이지 > 게시글 댓글 영역 추가 #463

- src/app/(shared)/(standard)/mypage/_components/CommentListRow/CommentListRow.styled.ts
- Closes #504 
- CommentListRow 탭, 모바일 반응형 구현
> [FEAT] CommentListRow 탭, 모바일 반응형 구현 #504

- src/app/(shared)/(standard)/mypage/community/comments/page.tsx
- src/app/(shared)/(standard)/mypage/community/likes/comments/page.tsx
- src/app/(shared)/(standard)/mypage/community/likes/posts/page.tsx
- src/app/(shared)/(standard)/mypage/community/posts/page.tsx
- src/app/(shared)/(standard)/mypage/community/saves/page.tsx
- src/hooks/useUrlSearchParams.ts
- Closes #513 
- date params 을 저희 데이터 전송 형식에 맞게 수정했습니다. 이제 2025.09.24T01030Z 이런 긴 문자로 안될겁니당
https://github.com/user-attachments/assets/edb6e8a3-19f6-495b-b074-161b91379f95
> [FIX] searchfilter date params #513

- src/app/(shared)/(standard)/mypage/_components/CommentListRow/CommentListRow.styled.ts
- src/app/(shared)/(standard)/mypage/_components/CommentListRow/CommentListRow.tsx
- src/app/(shared)/(standard)/mypage/community/posts/page.styled.ts
- Closes #533 
- 마이 > 커뮤니티 [선택]버튼이 왼쪽, 최신순 정렬 필터 오른쪽
- 마이 > 댓글 카드에 원글 화살표 없애기
> [FIX] 마이페이지 qa 이슈 해결 #533

- src/components/organisms/PostCard/PostCardDesktop/PostCardDesktop.tsx
- Closes #547 
- 게시글 카드에서 상세페이지로 이동 조건을 "카테고리가 사색/고민"이거나 "회원"이거나 로 수정하였습니다
> [FIX] PostCard 회원/비회원 처리 수정 #547

- src/components/molecules/CommentField/CommentField.tsx
- Closes #551 
- 한글 IME 중복 입력, 키 꾹 눌렀을 때 중복 이벤트 차단
=> 한글/일본어 같은 IME 입력 중에는 Enter 키 이벤트가 여러 번 발생해서 한글 입력 중 엔터를 하면 중복 이벤트가 발생하여 API 2번 호출 된다고 합니다!
=> 추가해서 키를 꾹 눌렀을때 api 요청이 여러번 가는 것도 막아뒀습니다!
> [FIX] 댓글 입력 시 IME 조합/키 반복으로 인한 중복 submit 방지 #551

- src/app/(shared)/(standard)/community/post/[id]/_components/PostAuthor/PostAuthor.tsx
- src/components/molecules/CommentField/CommentField.styled.ts
- Closes #556 
- 상세조회 페이지 익명 표시 X 수정 -> null 처리
- 크롬에서는 안깨지는데 사파리에서는 레이아웃이 깨져서 수정하였습니다!
textarea에 고정 높이가 들어가있다보니 크롬에서는 자동으로 오버플로우 안되게 밀어주는데 사파리에서는 안밀어주나봐요 그래서 고정 높이 없앴습니다!
> [FIX] 익명 처리, 댓글 입력란 반응형 수정 #556
